hangup:
  name: Hangup extension
  description: Hangup the current call of a extension.
  target:
  fields:
    channel:
      name: Channel
      description: The excact channel name to be hangup
      required: true
      example: "PJSIP/100"
originate:
  name: Originate call
  description: Create a call.
  target:
  fields:
    channel:
      name: Channel
      description: Channel name to call.
      required: true
      example: PJSIP/100
    exten:
      name: Extension
      description: Extension to use (requires Context and Priority)
      required: false
      example: "100"
    context:
      name: Context
      description: Context to use (requires Exten and Priority)
      required: false
      example: "default"
      default: "default"
    priority:
      name: Priority
      description: Priority to use (requires Exten and Context)
      required: false
      example: "1"
      default: "1"
    timeout:
      name: Timeout
      description: How long to wait for call to be answered (in ms)
      required: false
      example: "60000"
    application:
      name: Application
      description: Application to execute
      required: false
    data:
      name: Data
      description: Data to use (requires Application)
      required: false
    caller_id:
      name: CallerID
      description: CallerID to be set on the outgoing channel
      required: false
    earlymedia:
      name: Early Media
      description: Set to true to force call bridge on early media
      required: false
      default: true
    account:
      name: Account
      description: Account code
      required: false
    variables:
      name: Variables
      description: Channel variables
      required: false
      example: "key=val|key=val"
